# This is an example config file

# Paths to resources
star_ref: "/path/to/star/genome/index"
ref: "/path/to/reference/genome"
KGsnps: "/path/to/gatk-resources/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
millsIndels: "/path/to/gatk-resources/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
dbSNP: "/path/to/gatk-resources/dbsnp_146.hg38.vcf.gz"

# additional arguments to HaplotypeCaller
hcARgs: " -V ... -flag response"

# Optional VCF filtering -- pobably actually inlcude in hcArgs

refVCF: ".../PGC.filtered.vcf"


# Samples - points to forward read file.s

samples:
    SRR5938419: "SRR5938419_1_trimmed.fastq.gz"
    SRR5938420: "SRR5938420_1_trimmed.fastq.gz"
    SRR5938421: "SRR5938421_1_trimmed.fastq.gz"
    

